# Generated by Django 5.1.7 on 2025-05-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0016_rename_academy_student_school'),
        ('tutor', '0005_rename_phone_tutor_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_followed', to='students.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_followed', to='tutor.tutor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'tutor', 'academic_year'), name='unique_follow')],
            },
        ),
    ]
