# Generated by Django 5.1.7 on 2025-05-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
        ('students', '0017_rename_year_academy_student_year_of_arrival_and_more'),
        ('tutor', '0005_rename_phone_tutor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='follow',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_followed', to='students.student'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors_followed', to='tutor.tutor'),
        ),
    ]
