# Generated by Django 5.1.7 on 2025-05-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_alter_follow_student_alter_follow_tutor'),
        ('level', '0142_alter_level_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_followed', to='level.level'),
        ),
    ]
