# Generated by Django 5.1.7 on 2025-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0004_follow_level'),
        ('level', '0148_alter_level_effective'),
        ('students', '0020_remove_student_year_of_arrival'),
        ('tutor', '0005_rename_phone_tutor_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='registration_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('student', 'tutor', 'academic_year', 'registration_number'), name='unique_follow'),
        ),
    ]
