# Generated by Django 5.1.7 on 2025-05-04 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('users', '0053_remove_academy_academy_academy_school_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='not defined', max_length=100, null=True)),
                ('last_name', models.CharField(default='not defined', max_length=100, null=True)),
                ('starting_year_in_academy', models.DateField(null=True)),
                ('title', models.CharField(blank=True, default='not defined', max_length=100, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_academy_spec', to='school.School')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_spec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
