# Generated by Django 5.1.7 on 2025-05-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='not defined', max_length=20, null=True),
        ),
    ]
