# Generated by Django 5.1.7 on 2025-05-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academy',
        ),
    ]
