# Generated by Django 5.1.7 on 2025-05-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('teacher', '0003_remove_teacher_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_school_spec', to='school.school'),
        ),
    ]
