# Generated by Django 5.1.7 on 2025-06-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='starting_year_in_academy',
        ),
    ]
