# Generated by Django 5.1.7 on 2025-08-15 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='isAcademy',
            new_name='is_academy',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='isTeacher',
            new_name='is_teacher',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='isTutor',
            new_name='is_tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_tutor',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tutor',
            name='connexion_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='list_student_key',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userapp',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapp',
            name='connexion_key',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(default='not defined', max_length=254),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='password',
            field=models.CharField(default='not defined', null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='username',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(default='not defined', max_length=100)),
                ('place', models.CharField(default='', max_length=128)),
                ('director', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='academies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='not defined', max_length=100, null=True)),
                ('last_name', models.CharField(default='not defined', max_length=100, null=True)),
                ('coefficient', models.IntegerField(blank=True, default=None, null=True)),
                ('starting_year_in_academy', models.DateField(null=True)),
                ('title', models.CharField(blank=True, default='not defined', max_length=100, null=True)),
                ('level_key', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
