# Generated by Django 5.1.7 on 2025-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_academy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
