# Generated by Django 5.1.7 on 2025-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_academy_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='isAcademy',
            new_name='is_academy',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='isTeacher',
            new_name='is_teacher',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='isTutor',
            new_name='is_tutor',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userapp',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
