# Generated by Django 5.1.7 on 2025-03-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_isacademy_userapp_is_academy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='is_academy',
        ),
    ]
