# Generated by Django 5.1.7 on 2025-03-12 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_academy_is_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='academy', to=settings.AUTH_USER_MODEL),
        ),
    ]
