# Generated by Django 5.1.7 on 2025-03-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_academy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='user',
        ),
    ]
