# Generated by Django 5.1.7 on 2025-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_academy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='academy',
            name='place',
            field=models.CharField(default='', max_length=128),
        ),
    ]
