# Generated by Django 5.1.7 on 2025-03-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_academy_director_academy_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='activate',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='activate',
            new_name='active',
        ),
    ]
