# Generated by Django 5.1.7 on 2025-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_activate_teacher_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='academy',
            new_name='academy',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='academy',
            new_name='academy',
        ),
        migrations.AlterField(
            model_name='academy',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
