# Generated by Django 5.1.7 on 2025-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_academy_user_alter_teacher_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(default='not defined', max_length=50),
        ),
        migrations.AlterField(
            model_name='academy',
            name='academy',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
