# Generated by Django 5.1.7 on 2025-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_teacher_first_name_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
