# Generated by Django 5.1.7 on 2025-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_teacher_is_teacher_remove_tutor_is_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_key',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_key',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
