# Generated by Django 5.1.7 on 2025-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_teacher_user_key_tutor_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_connexion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_connexion',
            field=models.BooleanField(default=True),
        ),
    ]
