# Generated by Django 5.1.7 on 2025-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_teacher_first_connexion_tutor_first_connexion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_connexion',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='first_connexion',
        ),
        migrations.AddField(
            model_name='userapp',
            name='first_connexion',
            field=models.BooleanField(default=True),
        ),
    ]
