# Generated by Django 5.1.7 on 2025-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_teacher_first_connexion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='first_connexion',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
