# Generated by Django 5.1.7 on 2025-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_userapp_first_connexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='username',
            field=models.CharField(null=True),
        ),
    ]
