# Generated by Django 5.1.7 on 2025-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_userapp_email_alter_userapp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user_key',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user_key',
        ),
        migrations.AddField(
            model_name='userapp',
            name='user_key',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
