# Generated by Django 5.1.7 on 2025-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_teacher_user_key_remove_tutor_user_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='password',
            field=models.CharField(default='', null=True),
        ),
    ]
