# Generated by Django 5.1.7 on 2025-03-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userapp_email_alter_userapp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='password',
        ),
    ]
