# Generated by Django 5.1.7 on 2025-03-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_academy_email_remove_academy_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='nationality',
        ),
    ]
