# Generated by Django 5.1.7 on 2025-03-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_teacher_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='active',
        ),
    ]
