# Generated by Django 5.1.7 on 2025-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_teacher_active_remove_tutor_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
