# Generated by Django 5.1.7 on 2025-03-24 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userapp_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='user_key',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_key',
            field=models.CharField(default='not defined', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_key',
            field=models.CharField(default='not defined', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='starting_year_in_academy',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL),
        ),
    ]
