# Generated by Django 5.1.7 on 2025-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_userapp_user_key_teacher_teacher_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='starting_year_in_academy',
            field=models.DateField(null=True),
        ),
    ]
