# Generated by Django 5.1.7 on 2025-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0026_alter_level_effective'),
        ('subject', '0001_initial'),
        ('users', '0030_alter_teacher_first_name_alter_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_teacher_per_subject_per_level',
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('academy', 'level', 'subject'), name='unique_teacher_per_subject_per_level'),
        ),
    ]
