# Generated by Django 5.1.7 on 2025-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(default='not defined', max_length=254),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='password',
            field=models.CharField(default='not defined', null=True),
        ),
    ]
