# Generated by Django 5.1.7 on 2025-03-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='first_connexion',
        ),
    ]
