# Generated by Django 5.1.7 on 2025-04-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_student_key'),
        ('users', '0037_remove_userapp_first_connexion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tutor_key',
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_student', to='students.student', to_field='student_key'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL),
        ),
    ]
