# Generated by Django 5.1.7 on 2025-04-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_tutor_tutor_key_tutor_tutor_alter_tutor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor',
            new_name='student',
        ),
    ]
