# Generated by Django 5.1.7 on 2025-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_tutor_tutor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='key',
            field=models.CharField(default='not definied', max_length=100),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='password',
            field=models.CharField(default='not defined'),
        ),
    ]
