# Generated by Django 5.1.7 on 2025-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_userapp_key_alter_userapp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
