# Generated by Django 5.1.7 on 2025-04-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0058_alter_level_effective'),
        ('subject', '0003_alter_subject_academy'),
        ('users', '0041_alter_userapp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_academy', to='school.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_level', to='level.level'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_subject', to='subject.subject'),
        ),
    ]
