# Generated by Django 5.1.7 on 2025-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0063_alter_level_effective'),
        ('subject', '0004_alter_subject_academy'),
        ('users', '0043_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_teacher_per_subject_per_level',
        ),
        migrations.AddField(
            model_name='teacher',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('academy', 'level', 'subject', 'coefficient', 'teacher_key'), name='unique_teacher_key_per_academy_per_subject_per_level_per_coefficient'),
        ),
    ]
