# Generated by Django 5.1.7 on 2025-04-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_teacher_unique_teacher_per_subject_per_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='coefficient',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
