# Generated by Django 5.1.7 on 2025-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_teacher_coefficient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='student',
            new_name='student_key',
        ),
        migrations.AddField(
            model_name='tutor',
            name='connexion_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
    ]
