# Generated by Django 5.1.7 on 2025-05-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_sexe'),
        ('users', '0046_rename_student_tutor_student_key_tutor_connexion_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='student_key',
        ),
        migrations.AddField(
            model_name='tutor',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_student', to='students.student'),
        ),
    ]
