# Generated by Django 5.1.7 on 2025-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_tutor_student_key_tutor_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='student',
        ),
        migrations.AddField(
            model_name='tutor',
            name='list_student_key',
            field=models.JSONField(default=list),
        ),
    ]
