# Generated by Django 5.1.7 on 2025-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_tutor_student_tutor_list_student_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='key',
        ),
        migrations.AddField(
            model_name='userapp',
            name='connexion_key',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userapp',
            name='keys',
            field=models.JSONField(default=list),
        ),
    ]
