# Generated by Django 5.1.7 on 2025-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0088_alter_level_effective'),
        ('subject', '0006_alter_subject_category'),
        ('users', '0049_remove_userapp_key_userapp_connexion_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_teacher_key_per_academy_per_subject_per_level_per_coefficient',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_key',
            new_name='level_key',
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('academy', 'level', 'subject', 'coefficient', 'level_key'), name='unique_level_key_per_academy_per_subject_per_level_per_coefficient'),
        ),
    ]
