# Generated by Django 5.1.7 on 2025-05-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_remove_teacher_unique_teacher_key_per_academy_per_subject_per_level_per_coefficient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='keys',
        ),
    ]
