# Generated by Django 5.1.7 on 2025-05-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_userapp_keys'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_level_key_per_academy_per_subject_per_level_per_coefficient',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='level_key',
        ),
    ]
