# Generated by Django 5.1.7 on 2025-05-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_teacher_unique_level_key_per_academy_per_subject_per_level_per_coefficient_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='academy',
        #     name='academy',
        # ),
        # migrations.AddField(
        #     model_name='academy',
        #     name='school_name',
        #     field=models.CharField(default='not defined', max_length=100),
        # ),
        migrations.AddField(
            model_name='teacher',
            name='level_key',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
