# Generated by Django 5.1.7 on 2025-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_remove_academy_academy_academy_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
