# Generated by Django 5.1.7 on 2025-05-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0106_alter_level_effective'),
        ('subject', '0006_alter_subject_category'),
        ('users', '0054_alter_teacher_level_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_level', to='level.level'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_subject', to='subject.subject'),
        ),
        
    ]
