# Generated by Django 5.1.7 on 2025-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_teacher_level_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='password',
            field=models.CharField(default='not defined', null=True),
        ),
    ]
