# Generated by Django 5.1.7 on 2025-03-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.IntegerField()),
                ('year_academy', models.CharField(default='not defined', max_length=12)),
                ('repeating', models.IntegerField(default=1)),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students_level', to='level.level')),
            ],
        ),
    ]
