# Generated by Django 5.1.7 on 2025-03-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.tutor'),
        ),
    ]
