# Generated by Django 5.1.7 on 2025-03-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.tutor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_academy',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
