# Generated by Django 5.1.7 on 2025-03-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_initial'),
        ('students', '0003_alter_student_tutor_alter_student_year_school'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students_level', to='level.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.School'),
        ),
    ]
