# Generated by Django 5.1.7 on 2025-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_level_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='repeating',
            field=models.IntegerField(default=0),
        ),
    ]
