# Generated by Django 5.1.7 on 2025-03-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_repeating'),
        # ('users', '0016_teacher_first_name_teacher_last_name_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='student',
        #     name='tutor',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.tutor'),
        # ),
        migrations.AlterField(
            model_name='student',
            name='year_academy',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
