# Generated by Django 5.1.7 on 2025-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_tutor_alter_student_year_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_academy',
            field=models.IntegerField(null=True),
        ),
    ]
