# Generated by Django 5.1.7 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_key',
            field=models.CharField(default='not defined', max_length=100, unique=True),
        ),
    ]
