# Generated by Django 5.1.7 on 2025-04-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_student_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tutor',
        ),
    ]
