# Generated by Django 5.1.7 on 2025-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_student_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
