# Generated by Django 5.1.7 on 2025-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0055_alter_level_effective'),
        ('students', '0011_alter_student_student_key'),
        # ('users', '0039_rename_tutor_tutor_student'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('registration_number',), name='unique_registration_number'),
        ),
    ]
