# Generated by Django 5.1.7 on 2025-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0062_alter_level_effective'),
        ('students', '0012_student_unique_registration_number'),
        # ('users', '0043_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_registration_number',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('registration_number', 'student_key'), name='unique_registration_number_student_key'),
        ),
    ]
