# Generated by Django 5.1.7 on 2025-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_student_unique_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
