# Generated by Django 5.1.7 on 2025-05-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_sexe'),
        ('tutor', '0002_remove_tutor_connexion_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_tutor', to='tutor.tutor'),
        ),
    ]
