# Generated by Django 5.1.7 on 2025-05-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='academy',
            new_name='school',
        ),
    ]
