# Generated by Django 5.1.7 on 2025-05-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_rename_academy_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year_academy',
            new_name='year_of_arrival',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tutor',
        ),
    ]
