# Generated by Django 5.1.7 on 2025-05-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_rename_year_academy_student_year_of_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
