# Generated by Django 5.1.7 on 2025-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_student_level_remove_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='repeating',
        ),
    ]
