# Generated by Django 5.1.7 on 2025-05-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_repeating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_of_arrival',
        ),
    ]
