# Generated by Django 5.1.7 on 2025-05-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_student_year_of_arrival'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_registration_number_student_key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_key',), name='unique_student_key'),
        ),
    ]
