# Generated by Django 5.1.7 on 2025-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_student_unique_registration_number_student_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
