# Generated by Django 5.1.7 on 2025-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
