# Generated by Django 5.1.7 on 2025-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_student_registration_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_key',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_key', 'registration_number'), name='unique_student_key_registration_number'),
        ),
    ]
