# Generated by Django 5.1.7 on 2025-06-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('students', '0024_remove_student_unique_student_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school'),
        ),
    ]
