# Generated by Django 5.1.7 on 2025-05-04 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='not defined', max_length=100, null=True)),
                ('last_name', models.CharField(default='not defined', max_length=100, null=True)),
                ('list_student_key', models.JSONField(default=list)),
                ('connexion_key', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors_spec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
