# Generated by Django 5.1.7 on 2025-05-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='connexion_key',
        ),
    ]
