# Generated by Django 5.1.7 on 2025-05-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_remove_tutor_connexion_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='list_student_key',
        ),
    ]
