# Generated by Django 5.1.7 on 2025-05-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_tutor_list_student_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='address',
            field=models.CharField(default='not defined', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default='not defined', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(default='not defined', max_length=20, null=True),
        ),
    ]
