# Generated by Django 5.1.7 on 2025-05-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_tutor_address_tutor_email_tutor_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
