# Generated by Django 5.1.7 on 2025-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='place',
            new_name='address',
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='not defined', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(default='not defined', max_length=20, null=True),
        ),
    ]
