# Generated by Django 5.1.7 on 2025-05-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0001_initial'),
        ('level', '0104_alter_level_effective'),
        ('subject', '0006_alter_subject_category'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.level'),
        ),
        migrations.AddField(
            model_name='animation',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='animation',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
