# Generated by Django 5.1.7 on 2025-05-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0002_animation_level_animation_subject_animation_teacher'),
        # ('users', '0055_alter_teacher_level_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
