# Generated by Django 5.1.7 on 2025-05-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0003_animation_academy'),
        ('school', '0002_rename_place_school_address_school_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='academy',
        ),
        migrations.AlterField(
            model_name='animation',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
