# Generated by Django 5.1.7 on 2025-03-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_date',
        ),
    ]
