# Generated by Django 5.1.7 on 2025-05-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0004_remove_animation_academy_alter_animation_subject'),
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('subject', '0008_alter_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
