# Generated by Django 5.1.7 on 2025-05-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0005_animation_school_alter_animation_subject'),
        ('teacher', '0004_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
