# Generated by Django 5.1.7 on 2025-03-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0006_remove_course_level_remove_course_student_and_more'),
        ('participation', '0003_alter_participation_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
