# Generated by Django 5.1.7 on 2025-03-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='leader1',
        ),
        migrations.RemoveField(
            model_name='level',
            name='leader2',
        ),
        migrations.RemoveField(
            model_name='level',
            name='leader3',
        ),
    ]
