# Generated by Django 5.1.7 on 2025-03-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_remove_level_leader1_remove_level_leader2_and_more'),
        ('users', '0011_academy_director_academy_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='academy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='users.academy'),
        ),
    ]
