# Generated by Django 5.1.7 on 2025-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_level_group_level_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='series',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
