# Generated by Django 5.1.7 on 2025-03-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_level_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=40),
        ),
    ]
