# Generated by Django 5.1.7 on 2025-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0057_alter_level_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=19),
        ),
    ]
