# Generated by Django 5.1.7 on 2025-04-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0059_alter_level_effective'),
        ('users', '0043_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='academy',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='school.School'),
        ),
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=47),
        ),
    ]
