# Generated by Django 5.1.7 on 2025-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0060_alter_level_academy_alter_level_effective'),
        # ('users', '0043_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=46),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('name', 'group', 'series', 'academy'), name='unique_name_group_series_academy'),
        ),
    ]
