# Generated by Django 5.1.7 on 2025-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0061_alter_level_effective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=44),
        ),
    ]
