# Generated by Django 5.1.7 on 2025-04-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0072_alter_level_effective'),
        ('students', '0014_student_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='class_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_class_leader', to='students.student'),
        ),
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=46),
        ),
    ]
