# Generated by Django 5.1.7 on 2025-05-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0125_alter_level_effective'),
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('teacher', '0004_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='academy',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='school.school'),
        ),
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='level',
            name='head_teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_teachers_levels', to='teacher.teacher'),
        ),
    ]
