# Generated by Django 5.1.7 on 2025-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0126_alter_level_academy_alter_level_effective_and_more'),
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('students', '0016_rename_academy_student_school'),
        ('teacher', '0004_teacher_school'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='level',
            name='unique_name_group_series_academy',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='academy',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=35),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('name', 'group', 'series', 'school'), name='unique_name_group_series_school'),
        ),
    ]
