# Generated by Django 5.1.7 on 2025-05-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0127_remove_level_unique_name_group_series_academy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=45),
        ),
    ]
