# Generated by Django 5.1.7 on 2025-05-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0129_alter_level_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='effective',
            field=models.IntegerField(default=28),
        ),
    ]
