# Generated by Django 5.1.7 on 2025-06-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0150_alter_level_effective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='effective',
        ),
    ]
