# Generated by Django 5.1.7 on 2025-06-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0151_remove_level_effective'),
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('teacher', '0004_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='group',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        # migrations.AlterField(
        #     model_name='level',
        #     name='head_teacher',
        #     field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_teachers_levels', to='teacher.teacher'),
        # ),
        migrations.AlterField(
            model_name='level',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='school.School'),
        ),
        migrations.AlterField(
            model_name='level',
            name='series',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
