# Generated by Django 5.1.7 on 2025-08-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0152_alter_level_group_alter_level_head_teacher_and_more'),
        ('teacher', '0006_remove_teacher_starting_year_in_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='head_teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_teachers_levels', to='teacher.teacher'),
        ),
    ]
