# Generated by Django 5.1.7 on 2025-03-28 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('quiz', models.JSONField(blank=True, null=True)),
                ('exam', models.JSONField(blank=True, null=True)),
                ('cycle', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_level', to='level.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_student', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_subject', to='subject.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'level', 'subject', 'cycle', 'quiz'), name='unique_note')],
            },
        ),
    ]
