# Generated by Django 5.1.7 on 2025-03-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='score',
        ),
    ]
