# Generated by Django 5.1.7 on 2025-03-31 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_note_score'),
        # ('users', '0037_remove_userapp_first_connexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='note',
        #     name='teacher',
        #     field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_teachers', to='users.teacher'),
        # ),
    ]
