# Generated by Django 5.1.7 on 2025-04-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0052_alter_level_effective'),
        ('note', '0003_note_is_validated_note_teacher'),
        ('students', '0008_remove_student_name_student_first_name_and_more'),
        ('subject', '0001_initial'),
        # ('users', '0037_remove_userapp_first_connexion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note',
        ),
        migrations.AddField(
            model_name='note',
            name='academy',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        # migrations.AlterField(
        #     model_name='note',
        #     name='teacher',
        #     field=models.ForeignKey(default=5927, on_delete=django.db.models.deletion.CASCADE, related_name='notes_teachers', to='users.teacher'),
        # ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('student', 'level', 'subject', 'academy', 'cycle', 'quiz'), name='unique_note'),
        ),
    ]
