# Generated by Django 5.1.7 on 2025-04-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_unique_note_note_academy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
    ]
