# Generated by Django 5.1.7 on 2025-04-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_remove_note_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='quiz',
            new_name='score',
        ),
    ]
