# Generated by Django 5.1.7 on 2025-04-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0069_alter_level_effective'),
        ('note', '0007_rename_quiz_note_score'),
        ('students', '0013_remove_student_unique_registration_number_and_more'),
        ('subject', '0004_alter_subject_academy'),
        # ('users', '0045_alter_teacher_coefficient'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note',
        ),
        migrations.AlterField(
            model_name='note',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        # migrations.AlterField(
        #     model_name='note',
        #     name='teacher',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_teachers', to='users.teacher'),
        # ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('student', 'level', 'subject', 'academy', 'cycle', 'score'), name='unique_note'),
        ),
    ]
