# Generated by Django 5.1.7 on 2025-04-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_remove_note_unique_note_alter_note_academy_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note',
        ),
    ]
