# Generated by Django 5.1.7 on 2025-05-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_remove_note_academy_note_school'),
        ('teacher', '0004_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_teachers', to='teacher.teacher'),
        ),
    ]
