# Generated by Django 5.1.7 on 2025-05-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_alter_note_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='level',
        ),
        migrations.RemoveField(
            model_name='note',
            name='school',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='note',
            name='teacher',
        ),
    ]
