# Generated by Django 5.1.7 on 2025-05-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0005_animation_school_alter_animation_subject'),
        ('note', '0012_remove_note_level_remove_note_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_animation', to='animation.animation'),
        ),
    ]
