# Generated by Django 5.1.7 on 2025-05-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_note_animation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='coefficient',
        ),
    ]
