# Generated by Django 5.1.7 on 2025-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_remove_note_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='score',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
