# Generated by Django 5.1.7 on 2025-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_alter_note_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
    ]
