# Generated by Django 5.1.7 on 2025-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='not defined', max_length=100)),
                ('director', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='not defined', max_length=100, null=True)),
                ('phone_number', models.CharField(default='not defined', max_length=20, null=True)),
                ('address', models.CharField(default='not defined', max_length=255, null=True)),
            ],
        ),
    ]
