# Generated by Django 5.1.7 on 2025-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='password',
            field=models.CharField(default='not defined', max_length=100, null=True),
        ),
    ]
