# Generated by Django 5.1.7 on 2025-05-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0002_preregistration_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='password',
        ),
    ]
