# Generated by Django 5.1.7 on 2025-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0003_remove_preregistration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
