# Generated by Django 5.1.7 on 2025-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0004_preregistration_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='refused',
            field=models.BooleanField(default=False),
        ),
    ]
