# Generated by Django 5.1.7 on 2025-05-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0005_preregistration_refused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='preregistration',
            name='refused',
        ),
    ]
