# Generated by Django 5.1.7 on 2025-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0006_remove_preregistration_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='state',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
