# Generated by Django 5.1.7 on 2025-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SCIENCE', 'Science'), ('LITERATURE', 'Litterature'), ('ART', 'Art'), ('INFORMATIQUE', 'Computer_science'), ('AUTRE', 'Other'), ('DISCIPLINE', 'Discipline')], default='category', max_length=50)),
            ],
        ),
    ]
