# Generated by Django 5.1.7 on 2025-04-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('users', '0039_rename_tutor_tutor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
