# Generated by Django 5.1.7 on 2025-04-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_academy'),
        # ('users', '0041_alter_userapp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='academy',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
