# Generated by Django 5.1.7 on 2025-04-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_academy'),
        # ('users', '0043_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='academy',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
