# Generated by Django 5.1.7 on 2025-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_alter_subject_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('LITTERATURE', 'Litterature'), ('ART', 'Art'), ('INFORMATIQUE', 'Computer_science'), ('AUTRE', 'Other'), ('DISCIPLINE', 'Discipline')], default='category', max_length=50),
        ),
    ]
