# Generated by Django 5.1.7 on 2025-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_alter_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('LITERATURE', 'Littérature'), ('ART', 'Art'), ('COMPUTER_SCIENCE', 'Informatique'), ('OTHER', 'Autre'), ('DISCIPLINE', 'Discipline')], default='category', max_length=50),
        ),
    ]
