# Generated by Django 5.1.7 on 2025-05-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_place_school_address_school_email_and_more'),
        ('subject', '0006_alter_subject_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='academy',
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
