# Generated by Django 5.1.7 on 2025-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_remove_subject_academy_subject_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(default='category', max_length=50),
        ),
    ]
