# Generated by Django 5.1.7 on 2025-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_alter_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pseudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
