# Generated by Django 5.1.7 on 2025-03-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0006_remove_course_level_remove_course_student_and_more'),
        ('participation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animation.animation'),
        ),
    ]
